export const activoStatuses = [
    "ACTIVO", "FORMALIZADO", "MES_13", "FINALIZADA", "LIQUIDADO POR MC",
    "LIQUIDADO POR OP2", "LIQUIDADO POR MCO"
  ];
  
  export const canceladoStatuses = [
    "CANCELADO", "EXTINTO", "RECHAZADO", "INACTIVO", "BLOQUEADO", "SUSPENDIDO",
    "RECHAZADO POR MONTOS", "RECHAZADO POR BLOQUEO", "RECHAZADO POR OP1",
    "RECHAZADO POR MCO", "RECHAZADO POR MC", "RECHAZADO POR OP2",
    "NO LIQUIDADO POR MC", "NO LIQUIDADO POR OP2", "NO LIQUIDADO POR MCO"
  ];
  
  export const pendienteStatuses = [
    "PENDIENTE DE CAPTURAR", "PENDIENTE DE AUTORIZAR", "PENDIENTE",
    "PENDIENTE DE FORMALIZAR", "PENDIENTE CUMPLIMIENTO",
    "PENDIENTE DE CONSTITUIR"
  ];
  
  export const operacionStatuses = [
    "ENVIADA A ADMON", "CAPTURADO", "AUTORIZADO POR HONORARIOS",
    "AUTORIZADO POR MONTOS", "AUTORIZACIÓN INTERNA", "AUTORIZADO POR MC",
    "AUTORIZADO POR MCO", "AUTORIZADO POR OP1", "AUTORIZADO POR OP2",
    "AUTORIZADO POR FO", "AUTORIZADO Y PENDIENTE DE LIQUIDAR POR MC",
    "AUTORIZADO Y PENDIENTE DE LIQUIDAR POR OP2", "LAYOUT GENERADO"
  ];